### ISSUE TITLE
Get-GitRoot fails when building from a worktree

### ISSUE THREAD

**Issue by sandyarmstrong** [gundermanc/tools#65]
Git worktrees don't have a `.git` directory in their root, so `Get-GitRoot` thinks I'm not in a git repo, and reports "Not a git repository".

Then, the use of `$env:GitRoot` in my `.patchprofile` fails to work, and I cannot build.

Perhaps `Get-GitRoot` should execute `git rev-parse --show-toplevel` to get the git root directory. Of course that depends on `git` being available in `PATH`, or on the script using git from a VS install.

Commands like `ptbuild` overwrite `$env:GitRoot` so I can't just set it myself.

**Comment by sandyarmstrong** [comment]
Quickie fix working locally for me:

```pwsh
function Get-GitRoot()
{
    $root =  . git rev-parse --show-toplevel 2>$null
    if ($LASTEXITCODE -eq 0)
    {
        return Convert-Path $root
    }
    Write-Host -ForegroundColor Yellow "Not a git repository"
}
```

**Comment by gundermanc** [comment]
Thanks for the report, first-off, I'm thrilled this is still in use and you are probably one of ~2 people I know who have heard of 'work tree'.

Any chance you would like to send a PR?

**Comment by sandyarmstrong** [comment]
> Any chance you would like to send a PR?

Yeah, was planning on it, just need to change my fix to offer a fallback when `git.exe` isn't on the PATH.

**Comment by gundermanc** [comment]
Ok, should auto-update when you restart.
